[package]
name = "difftastic-wrapper"
version = "0.1.0"
authors = ["Ross Gardiner"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
tsify = "0.4.3"
wasm-bindgen = "0.2.83"

[profile.release]
opt-level = "s"

[package.metadata.wasm-pack.profile.profiling]
wasm-opt = false

[package.metadata.wasm-pack.profile.dev]
wasm-opt = false
